#!/bin/bash

echo "======================== CREATE VIDEO==================+"
echo mkdir temp
echo "cp *.jpg temp/."
echo "mogrify -resize 800x800  temp/*.jpg"
echo "convert temp/*.JPG -delay 10 -morph 10 temp/%05d.jpg"
echo "ffmpeg -r 25 -qscale 2  -i temp/%05d.jpg output.mp4"
echo "rm -R temp"



echo "======================== DECOMPOSE VIDEO==================+"
echo "convert DSCN3198.MOV im%05d.png"
